import { useState, useCallback, useEffect, useRef } from 'react';
import { MapView } from './components/MapView';
import { TimelineBar } from './components/TimelineBar';
import { InfoPanel } from './components/InfoPanel';
import { CategoryFilter } from './components/CategoryFilter';
import { DataExplorer } from './components/DataExplorer';
import { useTimeline } from './hooks/useTimeline';
import type { FeatureProperties, Category } from './types';
import type { StackInfo, ZoomRequest } from './components/MapView';
import { ALL_CATEGORIES, EVENT_CATEGORIES } from './theme/categories';

// Static seed data — generated by scripts/export-geojson.ts
// Replace with API call once the backend is running.
import seedData from './data/seed.geojson';

const geojson = seedData as GeoJSON.FeatureCollection;

export default function App() {
  const [currentPath, setCurrentPath] = useState(() => window.location.pathname);
  const timeline = useTimeline();
  const [selectedFeature, setSelectedFeature] = useState<FeatureProperties | null>(null);
  const [stack, setStack] = useState<StackInfo>({ index: 0, total: 1 });
  const [activeCategories, setActiveCategories] = useState<Set<Category>>(
    new Set([...EVENT_CATEGORIES, 'city'] as Category[]),
  );
  const [zoomRequest, setZoomRequest] = useState<ZoomRequest | null>(null);
  const zoomIdRef = useRef(0);

  useEffect(() => {
    const onPop = () => setCurrentPath(window.location.pathname);
    window.addEventListener('popstate', onPop);
    return () => window.removeEventListener('popstate', onPop);
  }, []);

  const navigate = useCallback((to: string) => {
    window.history.pushState({}, '', to);
    setCurrentPath(to);
  }, []);

  const handleToggleCategory = useCallback((cat: Category) => {
    setActiveCategories((prev) => {
      // All active → solo the clicked one
      if (prev.size === ALL_CATEGORIES.length) {
        return new Set([cat]);
      }
      const next = new Set(prev);
      if (next.has(cat)) {
        next.delete(cat);
        // Last one removed → reset to all
        if (next.size === 0) return new Set(ALL_CATEGORIES);
      } else {
        next.add(cat);
      }
      return next;
    });
  }, []);

  const handleSelectFeature = useCallback((props: FeatureProperties, stackInfo: StackInfo) => {
    setSelectedFeature(props);
    setStack(stackInfo);
  }, []);

  const handleClosePanel = useCallback(() => {
    setSelectedFeature(null);
  }, []);

  const handleNavigateToFeature = useCallback((feature: FeatureProperties) => {
    if (feature.yearStart !== null) {
      const cur = timeline.currentYear;
      const isLocation = feature.featureType === 'city' || feature.featureType === 'region' || feature.featureType === 'country';
      const activeNow = isLocation
        ? cur >= feature.yearStart && (feature.yearEnd == null || cur <= feature.yearEnd)
        : cur >= feature.yearStart && (feature.yearEnd != null ? cur <= feature.yearEnd : cur === feature.yearStart);
      if (!activeNow) {
        timeline.seek(feature.yearStart);
      }
    }
    navigate('/');
    setZoomRequest({ feature, id: ++zoomIdRef.current });
  }, [timeline, navigate]);

  if (currentPath === '/data') {
    return (
      <DataExplorer
        geojson={geojson}
        onBackToMap={() => navigate('/')}
        onNavigateToFeature={handleNavigateToFeature}
      />
    );
  }

  return (
    <div style={{ width: '100vw', height: '100vh', overflow: 'hidden', background: '#f8f9fa' }}>
      <CategoryFilter
        activeCategories={activeCategories}
        onToggle={handleToggleCategory}
        onOpenData={() => navigate('/data')}
      />

      <div style={{ position: 'absolute', inset: '52px 0 60px 0' }}>
        <MapView
          geojson={geojson}
          currentYear={timeline.currentYear}
          activeCategories={activeCategories}
          onSelectFeature={handleSelectFeature}
          zoomRequest={zoomRequest}
        />
      </div>

      <InfoPanel
        feature={selectedFeature}
        stack={stack}
        onClose={handleClosePanel}
        geojson={geojson}
        onNavigateToFeature={handleNavigateToFeature}
      />

      <TimelineBar
        currentYear={timeline.currentYear}
        stepSize={timeline.stepSize}
        stepOptions={timeline.stepOptions}
        isPlaying={timeline.isPlaying}
        playbackSpeed={timeline.playbackSpeed}
        onSeek={timeline.seek}
        onStep={timeline.step}
        onTogglePlay={timeline.togglePlay}
        onSetStepSize={timeline.setStepSize}
        onSetSpeed={timeline.setPlaybackSpeed}
      />
    </div>
  );
}
