"""
scripts/fetch-qid-labels.py

Fetches Wikidata English labels for every QID that appears in wikidataClasses
across seed.geojson, then writes frontend/src/data/wikidataLabels.ts.

Run this after any pipeline run + export to keep labels up to date.

Usage:
    python3 scripts/fetch-qid-labels.py
"""

import json
import re
import requests
import sys
import time
from pathlib import Path

ROOT = Path(__file__).parent.parent
GEOJSON_PATH = ROOT / "frontend/src/data/seed.geojson"
EXTRACT_PATH = ROOT / "pipeline/extract.py"
OUT_PATH = ROOT / "frontend/src/data/wikidataLabels.ts"

HEADERS = {"User-Agent": "OurStoryPipeline/1.0 (research project)"}


def collect_qids(geojson_path: Path) -> set[str]:
    with open(geojson_path) as f:
        gj = json.load(f)
    qids: set[str] = set()
    for feature in gj["features"]:
        for qid in feature["properties"].get("wikidataClasses") or []:
            qids.add(qid)
    return qids


def fetch_labels(qids: list[str]) -> dict[str, str]:
    labels: dict[str, str] = {}
    total = len(qids)
    for i in range(0, total, 50):
        batch = qids[i : i + 50]
        ids = "%7C".join(batch)
        url = (
            f"https://www.wikidata.org/w/api.php"
            f"?action=wbgetentities&ids={ids}&props=labels&languages=en&format=json"
        )
        try:
            r = requests.get(url, headers=HEADERS, timeout=30)
            for qid, entity in r.json().get("entities", {}).items():
                label = entity.get("labels", {}).get("en", {}).get("value")
                if label:
                    labels[qid] = label
        except Exception as e:
            print(f"  Warning: batch {i//50 + 1} failed: {e}", file=sys.stderr)
        print(f"  {min(i + 50, total)}/{total} QIDs fetched...")
        time.sleep(0.3)
    return labels


def extract_comment_labels(extract_path: Path) -> dict[str, str]:
    """Fallback labels from inline comments in pipeline/extract.py."""
    pattern = re.compile(r'"(Q\d+)"[^#]+#\s*([^\n]+)')
    labels: dict[str, str] = {}
    content = extract_path.read_text()
    for qid, comment in pattern.findall(content):
        label = comment.strip()
        label = re.sub(r"\s*\(.*?\)\s*$", "", label).strip()
        label = re.sub(r"\s*—.*$", "", label).strip()
        if qid not in labels:
            labels[qid] = label
    return labels


def write_ts(labels: dict[str, str], out_path: Path) -> None:
    lines = [
        f"  {qid}: {json.dumps(label)},"
        for qid, label in sorted(labels.items(), key=lambda x: int(x[0][1:]))
    ]
    content = (
        "// QID → human-readable label lookup.\n"
        "// Generated by scripts/fetch-qid-labels.py — re-run after each pipeline export.\n"
        f"// {len(labels)} entries\n"
        "export const WIKIDATA_LABELS: Record<string, string> = {\n"
        + "\n".join(lines)
        + "\n};\n"
    )
    out_path.write_text(content)


def main() -> None:
    print(f"Reading QIDs from {GEOJSON_PATH}...")
    qids = collect_qids(GEOJSON_PATH)
    print(f"Found {len(qids)} unique QIDs.")

    print("Fetching labels from Wikidata...")
    fetched = fetch_labels(sorted(qids, key=lambda q: int(q[1:])))

    print("Loading fallback labels from extract.py comments...")
    fallbacks = extract_comment_labels(EXTRACT_PATH)

    # Wikidata API labels take priority over comment labels
    merged = {**fallbacks, **fetched}

    covered = qids & set(merged.keys())
    missing = qids - set(merged.keys())
    print(f"\nCoverage: {len(covered)}/{len(qids)} QIDs labelled.")
    if missing:
        print(f"No English label on Wikidata for: {sorted(missing)}")

    write_ts(merged, OUT_PATH)
    print(f"Wrote {len(merged)} labels to {OUT_PATH}")


if __name__ == "__main__":
    main()
