// Wikipedia language editions, sorted alphabetically by English name.
// Each entry: [langCode, nativeName, englishName]
export const WIKIPEDIA_LANGUAGES: [string, string, string][] = [
  ['af', 'Afrikaans', 'Afrikaans'],
  ['sq', 'Shqip', 'Albanian'],
  ['ar', 'العربية', 'Arabic'],
  ['an', 'Aragonés', 'Aragonese'],
  ['hy', 'Հայերեն', 'Armenian'],
  ['ast', 'Asturianu', 'Asturian'],
  ['az', 'Azərbaycanca', 'Azerbaijani'],
  ['eu', 'Euskara', 'Basque'],
  ['be', 'Беларуская', 'Belarusian'],
  ['bn', 'বাংলা', 'Bengali'],
  ['bs', 'Bosanski', 'Bosnian'],
  ['br', 'Brezhoneg', 'Breton'],
  ['bg', 'Български', 'Bulgarian'],
  ['ca', 'Català', 'Catalan'],
  ['ceb', 'Cebuano', 'Cebuano'],
  ['zh', '中文', 'Chinese'],
  ['co', 'Corsu', 'Corsican'],
  ['hr', 'Hrvatski', 'Croatian'],
  ['cs', 'Čeština', 'Czech'],
  ['da', 'Dansk', 'Danish'],
  ['nl', 'Nederlands', 'Dutch'],
  ['en', 'English', 'English'],
  ['eo', 'Esperanto', 'Esperanto'],
  ['et', 'Eesti', 'Estonian'],
  ['fo', 'Føroyskt', 'Faroese'],
  ['fi', 'Suomi', 'Finnish'],
  ['fr', 'Français', 'French'],
  ['fy', 'Frysk', 'Frisian'],
  ['gl', 'Galego', 'Galician'],
  ['ka', 'ქართული', 'Georgian'],
  ['de', 'Deutsch', 'German'],
  ['el', 'Ελληνικά', 'Greek'],
  ['gu', 'ગુજરાતી', 'Gujarati'],
  ['ht', 'Kreyòl ayisyen', 'Haitian Creole'],
  ['he', 'עברית', 'Hebrew'],
  ['hi', 'हिन्दी', 'Hindi'],
  ['hu', 'Magyar', 'Hungarian'],
  ['is', 'Íslenska', 'Icelandic'],
  ['id', 'Bahasa Indonesia', 'Indonesian'],
  ['ga', 'Gaeilge', 'Irish'],
  ['it', 'Italiano', 'Italian'],
  ['ja', '日本語', 'Japanese'],
  ['jv', 'Basa Jawa', 'Javanese'],
  ['kn', 'ಕನ್ನಡ', 'Kannada'],
  ['kk', 'Қазақша', 'Kazakh'],
  ['ko', '한국어', 'Korean'],
  ['ku', 'Kurdî', 'Kurdish'],
  ['ky', 'Кыргызча', 'Kyrgyz'],
  ['la', 'Latina', 'Latin'],
  ['lv', 'Latviešu', 'Latvian'],
  ['lt', 'Lietuvių', 'Lithuanian'],
  ['lb', 'Lëtzebuergesch', 'Luxembourgish'],
  ['mk', 'Македонски', 'Macedonian'],
  ['mg', 'Malagasy', 'Malagasy'],
  ['ms', 'Bahasa Melayu', 'Malay'],
  ['ml', 'മലയാളം', 'Malayalam'],
  ['mt', 'Malti', 'Maltese'],
  ['mr', 'मराठी', 'Marathi'],
  ['mn', 'Монгол', 'Mongolian'],
  ['my', 'မြန်မာဘာသာ', 'Burmese'],
  ['ne', 'नेपाली', 'Nepali'],
  ['no', 'Norsk bokmål', 'Norwegian'],
  ['nn', 'Norsk nynorsk', 'Norwegian Nynorsk'],
  ['oc', 'Occitan', 'Occitan'],
  ['fa', 'فارسی', 'Persian'],
  ['pl', 'Polski', 'Polish'],
  ['pt', 'Português', 'Portuguese'],
  ['pa', 'ਪੰਜਾਬੀ', 'Punjabi'],
  ['ro', 'Română', 'Romanian'],
  ['ru', 'Русский', 'Russian'],
  ['sa', 'संस्कृतम्', 'Sanskrit'],
  ['gd', 'Gàidhlig', 'Scottish Gaelic'],
  ['sr', 'Српски', 'Serbian'],
  ['sd', 'سنڌي', 'Sindhi'],
  ['si', 'සිංහල', 'Sinhala'],
  ['sk', 'Slovenčina', 'Slovak'],
  ['sl', 'Slovenščina', 'Slovenian'],
  ['so', 'Soomaali', 'Somali'],
  ['es', 'Español', 'Spanish'],
  ['su', 'Basa Sunda', 'Sundanese'],
  ['sw', 'Kiswahili', 'Swahili'],
  ['sv', 'Svenska', 'Swedish'],
  ['tl', 'Tagalog', 'Tagalog'],
  ['tg', 'Тоҷикӣ', 'Tajik'],
  ['ta', 'தமிழ்', 'Tamil'],
  ['tt', 'Татарча', 'Tatar'],
  ['te', 'తెలుగు', 'Telugu'],
  ['th', 'ไทย', 'Thai'],
  ['tr', 'Türkçe', 'Turkish'],
  ['tk', 'Türkmençe', 'Turkmen'],
  ['uk', 'Українська', 'Ukrainian'],
  ['ur', 'اردو', 'Urdu'],
  ['ug', 'ئۇيغۇرچە', 'Uyghur'],
  ['uz', 'Oʻzbekcha', 'Uzbek'],
  ['vi', 'Tiếng Việt', 'Vietnamese'],
  ['cy', 'Cymraeg', 'Welsh'],
  ['yi', 'ייִדיש', 'Yiddish'],
  ['yo', 'Yorùbá', 'Yoruba'],
];

export const LANG_CODE_TO_NAME: Record<string, string> =
  Object.fromEntries(WIKIPEDIA_LANGUAGES.map(([code, , en]) => [code, en]));
